### ISSUE TITLE
Great library, hope to have wiki documents

### ISSUE THREAD

**Issue by activeliang** [YusukeIwaki/puppeteer-ruby#1]
Great library, hope to have wiki documents

**Comment by YusukeIwaki** [comment]
Thank you for your kind comment.

I'm now developing hard, and often make breaking changes.

I wonder

* Document automation with YARD in heavy development
* Creating api.md (like [this](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md)) after stable release.

If you have another good idea, please provide it :)

**Comment by YusukeIwaki** [comment]
YARD documentation is now available.
https://yusukeiwaki.github.io/puppeteer-ruby/

If more usage examples are wanted, feel free to create issues and pull requests at https://github.com/YusukeIwaki/puppeteer-ruby-example
