### ISSUE TITLE
Gem is not working

### ISSUE THREAD

**Issue by leodeoz** [YusukeIwaki/puppeteer-ruby#110]
### I'm trying to run these puppetter gem for doing some test, but following the basic instructions about installing, and creating a simple sample as the first example shown, i got this: 
![image](https://user-images.githubusercontent.com/13904047/120043716-d612c300-bfe2-11eb-96d9-575993340abc.png)

Which makes me thinks what's wrong? I've tested in two diff machines 1 windows and 1 linux. Both same issue. Just installing and running the sample.

Could you please advice? Thanks!

**Comment by YusukeIwaki** [comment]
Thank you for using this gem.
How did you install `puppeteer-ruby` ? ( `gem install puppeteer-ruby` or `bundle install` ?)

**Comment by leodeoz** [comment]
HI! Yes, "gem install puppeteer-ruby" as shown in Readme.

**Comment by YusukeIwaki** [comment]
I always used `bundle install` and didn't checked `gem install puppeteer-ruby`, but it worked for my Ubuntu environment.
![image](https://user-images.githubusercontent.com/11763113/120200171-0070b480-c25f-11eb-8e96-2b3f7fd50ad1.png)

Your screenshot shows `inspec`. Do you use `inspec` instead of `ruby` command in CLI?

**Comment by a6b8** [comment]
i had a similar problem.

 i checked ```gem list``` and the problem was i that had also a gem called 'puppeteer' installed. ```gem uninstall puppeteer``` fixed the problem. hope it helps.

**Comment by YusukeIwaki** [comment]
I tried

```
gem install puppeteer
gem install puppeteer-ruby
irb
> require 'puppeteer'
```

However no error occured...

Further information is required for investing this issue.
