### ISSUE TITLE
concurrent_ruby_utils.rb:45: syntax error, unexpected keyword_rescue, expecting keyword_end

### ISSUE THREAD

**Issue by yossi-shasho** [YusukeIwaki/puppeteer-ruby#118]
### Step To Reproduce / Observed behavior
2. add gem to gemfile
3. in rails console, type in `require 'puppeteer'`
4. error: 
```SyntaxError: /Users/USERNAME/.rvm/gems/ruby-2.4.1@fgc-marketplace/gems/puppeteer-ruby-0.32.4/lib/puppeteer/concurrent_ruby_utils.rb:45: syntax error, unexpected keyword_rescue, expecting keyword_end
    rescue Puppeteer::TimeoutError
          ^
/Users/USERNAME/.rvm/gems/ruby-2.4.1@fgc-marketplace/gems/puppeteer-ruby-0.32.4/lib/puppeteer/concurrent_ruby_utils.rb:61: syntax error, unexpected keyword_end, expecting end-of-input
	from (irb):1
```
 
### Expected behavior
module should load without errors

### Environment
macOS 11.4
rails 5.2.4.1
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]

**Comment by YusukeIwaki** [comment]
Thank you for reporting.

This gem is not tested with Ruby <= 2.5, and it seems that error is caused by `rescue` inside block. The feature is introduced on Ruby 2.5. Ruby 2.4 cannot interpet it.
https://bigbinary.com/blog/ruby-2.5-allows-rescue-inside-do-end-blocks

**Comment by yossi-shasho** [comment]
same thing happens to me now with `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin20]`
