### ISSUE TITLE
support for reusing cookies

### ISSUE THREAD

**Issue by jtoy** [YusukeIwaki/puppeteer-ruby#141]
is there a way to save the current cookie and load it in the next session? I didnt see in the docs or examples but I know regular puppeteer supports it.

**Comment by YusukeIwaki** [comment]
Hi, do you mean that you want `Page#cookies` and `Page#setCookie` ?

They are already available as `page.cookies` and `page.set_cookie`

**Comment by jtoy** [comment]
yes, i couldnt tell from documents. thanks
