### ISSUE TITLE
undefined method `setDefaultNavigationTimeout' for Puppeteer::Page

### ISSUE THREAD

**Issue by inspire22** [YusukeIwaki/puppeteer-ruby#161]
Hi!

This worked with an earlier version but doesn't anymore:
@page.setDefaultNavigationTimeout(0); 
NoMethodError (undefined method `setDefaultNavigationTimeout' for #<Puppeteer::Page:0x00007fa27404f808>

In the docs I see references to Puppeteer::TimeoutSettings but I cant' figure out to assign it...

Thanks for a great project!

**Comment by YusukeIwaki** [comment]
@inspire22 Thank you for your interest in this Gem. Could you try `page.default_navigation_timeout = 0` ?

https://github.com/YusukeIwaki/puppeteer-ruby/blob/main/docs/api_coverage.md
This document shows the Ruby version of method name for each JS method.
![image](https://user-images.githubusercontent.com/11763113/140320447-87646b40-43a4-4ded-8690-9152c483818e.png)

**Comment by YusukeIwaki** [comment]
Feel free to repopen if needed. Thank you.

**Comment by inspire22** [comment]
Working great, thanks!
