### ISSUE TITLE
Setting timeout: 0 in wait_for_function should disable the timeout

### ISSUE THREAD

**Issue by davidmles** [YusukeIwaki/puppeteer-ruby#164]
### Step To Reproduce / Observed behavior

`page.wait_for_function('() => document.querySelector("body").innerText.includes("Something")', timeout: 0)`

### Expected behavior

`wait_for_function` should  continue waiting without limit.
Currently it waits for 0ms.

### Environment

ruby 3.0.2p107

This was also reported and fixed in the JS version of Puppeteer here: https://github.com/puppeteer/puppeteer/issues/1920

**Comment by YusukeIwaki** [comment]
Hi, thank you for the king bug reporting. I will fix it soon.

**Comment by YusukeIwaki** [comment]
puppeteer-ruby 0.37.2 would fix this issue.
Thank you.

**Comment by davidmles** [comment]
That was quick. Thanks!
