### ISSUE TITLE
Browser appears as a white square with transparent edges

### ISSUE THREAD

**Issue by Randall-Coding** [YusukeIwaki/puppeteer-ruby#198]
### Step To Reproduce / Observed behavior
Just using the demo code, launch a new browser window with headless:false.  The browser looks like the image below 

![snippet_20220217-134418](https://user-images.githubusercontent.com/39175191/154559108-83ed944a-ec8c-4981-bc26-d236ac4d8203.png)

### Expected behavior
Should be able to see the webpage visited

### Environment
Ruby 2.7.5, Rails 5.2.6, Puppeteer-ruby (0.40.3), Ubuntu 21.04.

### Paste the output of `ruby --version`

Using rvm so it's a different ruby version

**Comment by Randall-Coding** [comment]
Also errors while running query_selector on the page.  

(byebug) page.query_selector("html")
> *** RuntimeError Exception: Bug of puppeteer-ruby...
> nil

**Comment by YusukeIwaki** [comment]
@Randall-Coding  Hi, could you let me know which version of Chromium is installed on your Ubuntu?

**Comment by Randall-Coding** [comment]
> @Randall-Coding Hi, could you let me know which version of Chromium is installed on your Ubuntu?

Chromium 98.0.4758.102 snap
