### ISSUE TITLE
Problem on heroku

### ISSUE THREAD

**Issue by aluisioalves123** [YusukeIwaki/puppeteer-ruby#210]
hello guys i'm having problems trying to run puppeteer on heroku. I always get the error as if chrome is not installed. I already installed puppeteer-heroku-buildpack
 but still I was not successful. Does anyone know how to handle this situation? Thanks

**Comment by YusukeIwaki** [comment]
@aluisioalves123  Sorry for late response,

puppeteer-heroku-buildpack doesn't contain Chrome or Chromium installation.
https://github.com/jontewks/puppeteer-heroku-buildpack/blob/main/bin/compile

And puppeteer-ruby doesn't have Chromium downloading feature.
One solution is that installing another buildpack for installing Chrome, like this: https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-google-chrome

Another solution (recommended) is to use Heroku Container Registry. 
https://qiita.com/YusukeIwaki/items/37c5e7be3fe1116c60ec (Sorry, in Japanese. DeepL will translate this well :)

**Comment by aluisioalves123** [comment]
hello, thanks for the reply, I finnaly manage to solve it. I installed the google chrome buildpack on heroku:

https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-google-chrome

I ran heroku buildpacks:add heroku/google-chrome on my project and it worked.
