### ISSUE TITLE
Specify 

### ISSUE THREAD

**Issue by Overload119** [YusukeIwaki/puppeteer-ruby#222]
I noticed in API Coverage:

Puppeteer version: v13.5.2
puppeteer-ruby version: 0.40.7

How would one upgrade the Puppeteer version?

I'm asking because currently I cannot load casper.com from Puppeteer. 
It shows Browser not supported error message.

**Comment by YusukeIwaki** [comment]
@Overload119  Hi, sorry for late response.

The API coverage doc is automatically generated by development/generate_api_coverage.rb 
https://github.com/YusukeIwaki/puppeteer-ruby/blob/950b63c6e55b1f28c994b503ef3e2b8731b0fcf2/development/generate_api_coverage.rb#L272

The version of Puppeteer described in the doc is just a name of the git tag in the puppeteer/puppeteer repository.
Note that the documentation doesn't mention about the compatibility of behaviors of Puppeteer(JS) and puppeteer-ruby. It just shows the list of the available APIs defined in Puppeteer(JS)
