### ISSUE TITLE
Launch hangs in Dockerized setup

### ISSUE THREAD

**Issue by kalsan** [YusukeIwaki/puppeteer-ruby#278]
### Step To Reproduce / Observed behavior

Install according to documentation, require puppeteer and launch `Puppeteer.launch(args: ['--no-sandbox', '--disable-setuid-sandbox']) { puts 'test' }`

### Expected behavior

Startup, puts test and terminate

### Actual behavior

Hangs indefinitively without outputting anything. Analysis shows that it waits in `chrome_target_manager.rb:65`.

### Environment

- Ruby `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]`
- Docker `Docker version 20.10.21, build baeda1f`
- Base Image `fedora:34`
- Chrome: `Chromium 90.0.4430.212 Fedora Project`, the command is `chromium-browser`

**Comment by YusukeIwaki** [comment]
I tried the similar code on Ruby 3.1 on Alpine Linux, and it worked as expected.

```Dockerfile
FROM ruby:3.1-alpine

WORKDIR /app

COPY Gemfile /app/Gemfile

RUN apk update \
    && apk add --no-cache --virtual build-deps \
    build-base \
    && bundle install \
    && apk del build-deps

RUN apk update \
    && apk add --no-cache \
    chromium \
    font-noto \
    fontconfig \
    && wget https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip \
    && mkdir -p /usr/share/fonts/NotoSansCJKjp \
    && unzip NotoSansCJKjp-hinted.zip -d /usr/share/fonts/NotoSansCJKjp/ \
    && rm NotoSansCJKjp-hinted.zip \
    && fc-cache -fv

ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser
```

```
/app # ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-musl]
/app # chromium-browser --version
Chromium 102.0.5005.182 
```

```ruby
require 'puppeteer'

launch_options = {
  executable_path: ENV['PUPPETEER_EXECUTABLE_PATH'],
  args: ['--no-sandbox', '--disable-setuid-sandbox'],
}
Puppeteer.launch(**launch_options) do |browser|
  page = browser.pages.first || browser.new_page
  page.goto("https://github.com/YusukeIwaki")
  page.screenshot(path: "1.capture_a_site_chromium.png")
end
```

**Comment by YusukeIwaki** [comment]
Chromium 90 seems a little old. Could you try the script on the latest Chromium?

**Comment by kalsan** [comment]
@YusukeIwaki thank you very much for your helpful reply. Indeed, updating Chromium solves the problem. Thank you and have a nice day!
