### ISSUE TITLE
Is there a port Pupetteer can reach testing environment?

### ISSUE THREAD

**Issue by cyclingzealot** [YusukeIwaki/puppeteer-ruby#315]
If I'm using a pupetteer script to produce PDFs of rails server web pages and I'm developing automated tests for it, is there a port where the *testing* environment would be listening for http connections?

**Comment by YusukeIwaki** [comment]
Please check these articles:

- https://dev.to/yusukeiwaki/system-testing-for-rails-application-without-capybara-using-puppeteer-5882 for completely independent of Capybara.
- https://playwright-ruby-client.vercel.app/docs/article/guides/rails_integration_with_null_driver for using Capybara required at least.
