### ISSUE TITLE
qualizy -> quality ?

### ISSUE THREAD

**Issue by kmuto** [YusukeIwaki/puppeteer-ruby#40]
ライブラリで遊ばせていただいています。

https://github.com/YusukeIwaki/puppeteer-ruby/blob/62ae912f57910a4b480af93cb63f93ce6d07439a/lib/puppeteer/page/screenshot_options.rb#L42

ここ、qualizy→quality ではないでしょうか(現状このパラメータを使ってみるとエラーになりました)。

**Comment by YusukeIwaki** [comment]
ありがとうございます。
そのとおりです。修正します！

**Comment by YusukeIwaki** [comment]
@kmuto https://rubygems.org/gems/puppeteer-ruby/versions/0.0.26 で対応しました。
