### ISSUE TITLE
`<main>': undefined method `launch' for Puppeteer:Module (NoMethodError)

### ISSUE THREAD

**Issue by DaBrondo** [YusukeIwaki/puppeteer-ruby#49]
So, just tried the gem and the examples do not work:

`<main>': undefined method `launch' for Puppeteer:Module (NoMethodError)

Any ideas?

Thanks!
Greg B.

**Comment by YusukeIwaki** [comment]
Hi @DaBrondo, could you provide the output of `ruby --version` ?

**Comment by TheKidCoder** [comment]
@DaBrondo I think you made the same mistake I did. There is a gem named https://rubygems.org/gems/puppeteer that is not this gem. You'll need to install https://rubygems.org/gems/puppeteer-ruby

@YusukeIwaki Would be good to include this in the README. Opening a PR.
