### ISSUE TITLE
Not compatible with Windows

### ISSUE THREAD

**Issue by Jwiggiff** [YusukeIwaki/puppeteer-ruby#57]
### Step To Reproduce / Observed behavior
Launch puppeteer-ruby on Windows.

I get the following error:
`Failed to launch browser! No such file or directory - /usr/bin/google-chrome (Puppeteer::BrowserRunner::LaunchError)`

I believe this is because it assumes I am on linux and that google chrome is installed under /usr/bin.

### Expected behavior
opens a browser.

### Environment
Windows 10

Paste the output of `ruby --version`
`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]`

**Comment by YusukeIwaki** [comment]
@Jwiggiff Thank you for your feedback. Actually I don't have any Windows devices and I'm not sure but we can avoid the issue by specifying `executable_path` explicitly.

```
Puppeteer.launch(
  executable_path: 'C:\\Program Files\ (x86)\\Google\\Chrome\\Application\\Chrome.exe',
  headless: false,
) do |browser|
  page = browser.pages.last
  page.goto('http://xxx.example.com/')


end
```

So could you try this?
If you succeed in launching the puppeteer, I will set the default value for Windows devices in the next puppeteer-ruby release.

**Comment by Jwiggiff** [comment]
It does not seem to work. Here is the error I get:
```
Traceback (most recent call last):
        6: from test.rb:3:in `<main>'
        5: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.28.1/lib/puppeteer.rb:70:in `method_missing'
        4: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.28.1/lib/puppeteer.rb:70:in `public_send'
        3: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.28.1/lib/puppeteer.rb:140:in `launch'
        2: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.28.1/lib/puppeteer/launcher/chrome.rb:44:in `launch'
        1: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.28.1/lib/puppeteer/browser_runner.rb:115:in `start'
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.28.1/lib/puppeteer/browser_runner.rb:115:in `trap': unsupported signal `SIGHUP' (ArgumentError)
```

I have a feeling it is because I need a different executable than the normal Chrome one. Like some sort of headless-specific version. I'll let you know if I find a solution/

**Comment by YusukeIwaki** [comment]
It seems Chrome works well by specifying executable_path explicitly.

```
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puppeteer-ruby-0.28.1/lib/puppeteer/browser_runner.rb:115:in `trap': unsupported signal `SIGHUP' (ArgumentError)
```

This issue is caused by Ruby's behavior. The reference doc of `Signal#trap` says the Windows version of Ruby only accepts
 `INT` `ILL` `FPE` `SEGV` `TERM` `BREAK` `ABRT` `EXIT ` for the argument, because SIGHUP is only for macOS, Linux.

I believe the code below would bypass `.trap(SIGHUP)`

```
Puppeteer.launch(
  executable_path: 'C:\\Program Files\ (x86)\\Google\\Chrome\\Application\\Chrome.exe',
  handle_SIGHUP: false,
  headless: false,
) do |browser|
  page = browser.pages.last
  page.goto('http://xxx.example.com/')


end
```

after a modification in browser_runner.rb ( `@handle_SIGHUP = options[:handle_SIGHUP] || true` -> `@handle_SIGHUP = options[:handle_SIGHUP].nil?  true : options[:handle_SIGHUP]` )

**Comment by Jwiggiff** [comment]
The code posted above does not work, still get the same error. Any update?

**Comment by YusukeIwaki** [comment]
@Jwiggiff  puppeteer-ruby 0.31.0 would be compatible with Windows. Could you try this?
https://rubygems.org/gems/puppeteer-ruby/versions/0.31.0

**Comment by Jwiggiff** [comment]
Ah yes this version does seem to work now. Thank you! However I have now run into a new issue that the pdf function is not working correctly. Would you like me to create a new issue?
