### ISSUE TITLE
addStyleTag, addScriptTag, bypassCSP

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/puppeteer-ruby#63]
### Simple description about the feature

* https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pageaddscripttagoptions
* https://pptr.dev/#?product=Puppeteer&version=v5.5.0&show=api-pagesetbypasscspenabled

### Usecase / Motivation

rubycdp/ferrum already supports addStyleTag, addScriptTag, bypassCSP.
puppeteer-ruby should also support them.

**Comment by igorski89** [comment]
A little bit confusing that [Page#add_script_tag](https://yusukeiwaki.github.io/puppeteer-ruby-docs/Puppeteer/Page.html#add_script_tag-instance_method) is implemented alongside with [Puppeteer::Page::ScriptTag](https://yusukeiwaki.github.io/puppeteer-ruby-docs/Puppeteer/Page/ScriptTag.html), however the underlying implementation is actually missing, only the JS implementation commented-out https://github.com/YusukeIwaki/puppeteer-ruby/blob/master/lib/puppeteer/dom_world.rb#L237.

I imagine the actual implementation for the three methods shouldn't be that hard, in the meantime, at least add_script_tag could be implemented as follows:

```ruby
src = File.read(path)
add_script_tag_js = <<~JAVASCRIPT
(content) => {
    var scriptTag = document.createElement('script');
    scriptTag.type = 'text/javascript';
    scriptTag.text = content;
    document.head.appendChild(scriptTag);
}
JAVASCRIPT
await page.evaluate(add_script_tag_js, src)
```

**Comment by YusukeIwaki** [comment]
Yeah, Exactly.
I will implement them.
