### ISSUE TITLE
Using page.pdf doesn't work properly

### ISSUE THREAD

**Issue by Jwiggiff** [YusukeIwaki/puppeteer-ruby#72]
### Step To Reproduce / Observed behavior
In headless mode, go to any website and use `page.pdf` to save a pdf of the website.

A pdf is saved but it seems like the webpage is not loaded correctly, i.e. it doesn't look like the actual site.

### Expected behavior
It looks like the site in the browser.

### Environment
Windows 10

Paste the output of `ruby --version`
`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]`

**Comment by YusukeIwaki** [comment]
Thank you for the bug report.

I tested with the script below with puppeteer-ruby and Puppeteer (Node.js)

```
page.goto('https://dev.to/')
page.pdf(path: './dev_to.pdf')
```

The protocol log (SEND/RECV) shows the same data.

[data_node.txt](https://github.com/YusukeIwaki/puppeteer-ruby/files/6193848/data_node.txt)
[data_rb.txt](https://github.com/YusukeIwaki/puppeteer-ruby/files/6193845/data_rb.txt)

Probably unexpected PDF is produced in the base64-decode process on Windows. I will investigate the detail of it.

**Comment by YusukeIwaki** [comment]
@Jwiggiff puppeteer-ruby 0.31.1 would fix this bug. Thank you for your report :)
