### ISSUE TITLE
Unrecognized pdf format and margins

### ISSUE THREAD

**Issue by Jwiggiff** [YusukeIwaki/puppeteer-ruby#77]
### Step To Reproduce / Observed behavior
Open any page and attempt to print to pdf using the below options:
```
browser_page.pdf(
          path: "#{path}/generated_files/#{page.basename}.pdf",
          format: "letter",
          margin: "1cm"
        )
```

I get the following errors:
`lib/puppeteer/page/pdf_options.rb:107:in 'calc_paper_size': Unknown paper format: letter (ArgumentError)` and `lib/puppeteer/page/pdf_options.rb:118:in '[]': no implicit conversion of Symbol into Integer (TypeError)`

### Expected behavior
Create a letter pdf with 1cm margins all around.

### Environment
Windows 10

Paste the output of `ruby --version`
`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]`

Also, I'd be happy to make a PR with a more detailed pdf example in the examples repo once I get this figured out :)

**Comment by YusukeIwaki** [comment]
Also new option should be inclueed: https://github.com/puppeteer/puppeteer/pull/6981/files
